### Site info:
title: Harold TAMO
tagline: Odoo Developer
author: Harold TAMO
email: tamoharold@gmail.com
description: "Odoo Developer." # You can edit this line in _config.yml. It will appear in your document head meta and in your feed.xml site description
keywords: "Odoo, developer"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://haroldtamo.github.io" # the base hostname & protocol for your site
locale: en_US

### Personal info and site tools info:
twitter_username: haroldtamo
github_username:  haroldtamo
disqus_shortname: haroldtamo
linkedin_username: haroldtamo
gplus_username: haroldtamo
skype_username: haroldtamo
favicon:     ""
aboutme: Hi, I'm Harold TAMO. I'm  an Odoo developer at <a href="http://www.y-note.cm/author/h-tamo/">Y-note</a> # these are shown on aboutme-sidebar.
aboutme_photo: /images/profilhal.jpg # your photo.


### Site setting:
ShowContactInfo: "True" # Personal Info (twitter,github,email) can be seen on aboutme-sidebar, those info only shown when ShowContactInfo == True
default_column: "two" # blog style: two columns, if default_column != "two", you will see a one column blog.
default_locale: "en" # blog sidebar language set, only include: English(en) and Chinese (cn)

locales:
    en:
      Aboutme: "About Me"
      Archives: "Archives"
      Blogroll: "Blogroll"
      Categories: "Categories"
      Copyright_Notice: "Copyright Notice"
      Recent_Posts: "Recent Posts"
      Tags: "Tags"
      Previous: "Older"
      Next: "Newer"
      PostedInCategories: "Posted in"
      Taggedwith: "and tagged"  
      PostDate: "on "
    fr:
      À propos de moi: ""
      Archives: ""
      Blogroll: ""
      Categories: ""
      Copyright_Notice: ""
      Recent_Posts: ""
      Tags: ""
      Previous: ""
      Next: ""
      PostedInCategories: ""
      Taggedwith: ""
      PostDate: ""


### your Blogroll info, only name can shown on the page.

#Blogroll:
#   - name: Freshman21
#      href: http://yulijia.net/freshman21
#      title: Another Jekyll blog theme
#    - name: author's website
#      href: http://yulijia.net/
#      title: Lijia Yu's website


### Build settings
markdown: kramdown
highlighter: rouge
paginate: 5
